import type { ReactNode } from "react";
import { NOT_ENOUGH_CONTEXT } from "@/lib/forge-scene/mock";
import type { SceneCardFields } from "@/lib/forge-scene/types";

type GenerationSource = "mock" | "anthropic";

interface Props {
  card: SceneCardFields;
  source: GenerationSource;
}

function FieldValue({ value }: { value: string }) {
  const isEmpty = value.trim().toLowerCase() === NOT_ENOUGH_CONTEXT;
  return <p className={isEmpty ? "text-blue-100/40 italic" : "text-blue-100/90"}>{value}</p>;
}

function ListValue({ values, emptyLabel = NOT_ENOUGH_CONTEXT }: { values: string[]; emptyLabel?: string }) {
  if (values.length === 0) {
    return <p className="text-blue-100/40 italic">{emptyLabel}</p>;
  }
  return (
    <ul className="list-disc space-y-1 pl-5 text-blue-100/90">
      {values.map((value, index) => (
        <li key={index}>{value}</li>
      ))}
    </ul>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div>
      <h3 className="mb-1 text-xs font-semibold tracking-wide text-blue-100/60 uppercase">{label}</h3>
      {children}
    </div>
  );
}

export function SceneCard({ card, source }: Props) {
  return (
    <div className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-6">
      <div className="flex items-center justify-between">
        <span className="rounded-full bg-purple-500/20 px-3 py-1 text-xs font-medium tracking-wide text-purple-200 uppercase">
          Draft
        </span>
        <span className="text-xs text-blue-100/40">
          {source === "mock" ? "Mock generation" : "Generated by Claude"}
        </span>
      </div>

      <Field label="Player Goal">
        <FieldValue value={card.playerGoal} />
      </Field>

      <Field label="Obstacle">
        <FieldValue value={card.obstacle} />
      </Field>

      <Field label="Characters">
        {card.characters.length === 0 ? (
          <p className="text-blue-100/40 italic">none / not applicable</p>
        ) : (
          <ul className="list-disc space-y-1 pl-5 text-blue-100/90">
            {card.characters.map((character, index) => (
              <li key={index}>
                <span className="font-medium">{character.name}</span> — {character.function}
              </li>
            ))}
          </ul>
        )}
      </Field>

      <Field label="Interactive Element">
        <FieldValue value={card.interactiveElement} />
      </Field>

      <Field label="Required Assets">
        <ListValue values={card.requiredAssets} />
      </Field>

      <Field label="Design Risks">
        <ListValue values={card.designRisks.map((risk) => risk.risk)} />
      </Field>
    </div>
  );
}
