import { useState, type ReactNode } from "react";
import { NOT_ENOUGH_CONTEXT } from "@/lib/forge-scene/mock";
import { isReadyEligible } from "@/lib/forge-scene/readiness";
import { ServerError } from "@/components/auth/ServerError";
import { Button } from "@/components/ui/button";
import type { SceneCardRecord, SceneStatus } from "@/lib/forge-scene/types";

type GenerationSource = "mock" | "anthropic";

interface Props {
  sceneId: string;
  record: SceneCardRecord;
  source: GenerationSource;
  onSaved: (record: SceneCardRecord) => void;
}

interface CardUpdateResponse extends Partial<SceneCardRecord> {
  error?: string;
  missing?: string[];
}

const STATUS_OPTIONS: { value: SceneStatus; label: string }[] = [
  { value: "draft", label: "Draft" },
  { value: "needs_work", label: "Needs Work" },
  { value: "ready", label: "Ready" },
];

function FieldValue({ value }: { value: string }) {
  const isEmpty = value.trim().toLowerCase() === NOT_ENOUGH_CONTEXT;
  return <p className={isEmpty ? "text-blue-100/40 italic" : "text-blue-100/90"}>{value}</p>;
}

function ListValue({ values, emptyLabel = NOT_ENOUGH_CONTEXT }: { values: string[]; emptyLabel?: string }) {
  if (values.length === 0) {
    return <p className="text-blue-100/40 italic">{emptyLabel}</p>;
  }
  return (
    <ul className="list-disc space-y-1 pl-5 text-blue-100/90">
      {values.map((value, index) => (
        <li key={index}>{value}</li>
      ))}
    </ul>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div>
      <h3 className="mb-1 text-xs font-semibold tracking-wide text-blue-100/60 uppercase">{label}</h3>
      {children}
    </div>
  );
}

export function SceneCard({ sceneId, record, source, onSaved }: Props) {
  const [draft, setDraft] = useState<SceneCardRecord>(record);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { eligible, missingReasons } = isReadyEligible(draft);

  function toggleRisk(index: number) {
    setDraft((prev) => ({
      ...prev,
      designRisks: prev.designRisks.map((risk, i) =>
        i === index ? { ...risk, acknowledged: !risk.acknowledged } : risk,
      ),
    }));
  }

  async function save() {
    setSaving(true);
    setError(null);
    try {
      const response = await fetch(`/api/scenes/${sceneId}/card`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: draft.status, notes: draft.notes, designRisks: draft.designRisks }),
      });
      const body = (await response.json()) as CardUpdateResponse;

      if (!response.ok) {
        const detail = body.missing?.length ? `: ${body.missing.join(", ")}` : "";
        setError((body.error ?? "Could not save changes") + detail);
        return;
      }

      onSaved(body as SceneCardRecord);
    } catch {
      setError("Network error — could not reach the server");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-6">
      <div className="flex items-center justify-between">
        <div className="flex gap-2">
          {STATUS_OPTIONS.map((option) => {
            const disabled = option.value === "ready" && !eligible;
            const active = draft.status === option.value;
            return (
              <button
                key={option.value}
                type="button"
                disabled={disabled}
                title={disabled ? `Not ready: ${missingReasons.join(", ")}` : undefined}
                onClick={() => {
                  setDraft((prev) => ({ ...prev, status: option.value }));
                }}
                className={`rounded-full px-3 py-1 text-xs font-medium tracking-wide uppercase transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
                  active
                    ? "bg-purple-500/40 text-purple-100"
                    : "bg-purple-500/20 text-purple-200 hover:bg-purple-500/30"
                }`}
              >
                {option.label}
              </button>
            );
          })}
        </div>
        <span className="text-xs text-blue-100/40">
          {source === "mock" ? "Mock generation" : "Generated by Claude"}
        </span>
      </div>

      <Field label="Player Goal">
        <FieldValue value={draft.playerGoal} />
      </Field>

      <Field label="Obstacle">
        <FieldValue value={draft.obstacle} />
      </Field>

      <Field label="Characters">
        {draft.characters.length === 0 ? (
          <p className="text-blue-100/40 italic">none / not applicable</p>
        ) : (
          <ul className="list-disc space-y-1 pl-5 text-blue-100/90">
            {draft.characters.map((character, index) => (
              <li key={index}>
                <span className="font-medium">{character.name}</span> — {character.function}
              </li>
            ))}
          </ul>
        )}
      </Field>

      <Field label="Interactive Element">
        <FieldValue value={draft.interactiveElement} />
      </Field>

      <Field label="Required Assets">
        <ListValue values={draft.requiredAssets} />
      </Field>

      <Field label="Design Risks">
        {draft.designRisks.length === 0 ? (
          <p className="text-blue-100/40 italic">{NOT_ENOUGH_CONTEXT}</p>
        ) : (
          <ul className="space-y-1">
            {draft.designRisks.map((risk, index) => (
              <li key={index} className="flex items-start gap-2 text-blue-100/90">
                <input
                  type="checkbox"
                  checked={risk.acknowledged}
                  onChange={() => {
                    toggleRisk(index);
                  }}
                  className="mt-1 size-4 shrink-0 rounded border-white/30 bg-white/10"
                />
                <span className={risk.acknowledged ? "line-through opacity-60" : ""}>{risk.risk}</span>
              </li>
            ))}
          </ul>
        )}
      </Field>

      <Field label="Notes">
        <textarea
          value={draft.notes}
          onChange={(event) => {
            const { value } = event.target;
            setDraft((prev) => ({ ...prev, notes: value }));
          }}
          rows={3}
          placeholder="Freeform notes or corrections..."
          className="w-full rounded-lg border border-white/10 bg-white/10 p-2 text-sm text-blue-100/90 placeholder:text-blue-100/30 focus:border-purple-400/50 focus:outline-none"
        />
      </Field>

      <ServerError message={error} />

      <Button
        onClick={save}
        disabled={saving}
        className="w-full rounded-lg bg-purple-600 px-4 py-2 font-medium text-white transition-colors hover:bg-purple-500"
      >
        {saving ? "Saving..." : "Save"}
      </Button>
    </div>
  );
}
